GET http://localhost:3000/api/personas/

###

DELETE   http://localhost:3000/api/personas/66bac4a6e0edba8d8559275c
Content-Type: application/json

{
    "name": "ASDSADSDsad",
    "email": "ADS@gmail.com",
    "picture": "N/Aasdasd"
}